_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 55
            "4": 3.10.11
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
